spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/mapping?useSSL=false
spring.datasource.username=root
spring.datasource.password=Praveen@123
spring.jpa.hibernate.ddl-auto=create 