spring.application.name= spring boot tutorial 
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:/Users/rj/Documents/db
spring.datasource.username=praveen
spring.datasource.password=Anuj123
spring.jpa.hibernate.ddl-auto=create 