spring.application.name=spring-security

spring.datasource.url=jdbc:mysql://localhost:3306/mapping?useSSL=false
spring.datasource.username=root
spring.datasource.password=Praveen@123
spring.jpa.hibernate.ddl-auto=create

jwt.secret_key=djanfdjfnwjfnho12w34nzxmcndjfjffsdnsmdfwdqer345fsdfea 

spring.security.oauth2.client.registration.google.client-id=504921321248-kl2djkafsai4oohneb23vslmst4jpo26.apps.googleusercontent.com
